[daemonize]
# log_to = "syslog" or /file/path
log_to = "syslog"
pid_file = "/var/run/illuminanced.pid"
# log_level = "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
log_level = "ERROR"

[general]
check_period_in_seconds = 1
light_steps = 96
min_backlight = 5
step_barrier = 0.1
max_backlight_file = "/sys/class/backlight/nvidia_wmi_ec_backlight/max_brightness"
backlight_file = "/sys/class/backlight/nvidia_wmi_ec_backlight/brightness"
illuminance_file = "/sys/bus/iio/devices/iio:device0/in_illuminance_raw"
# illuminance_file = "/sys/bus/acpi/devices/ACPI0008:00/iio:device0/in_illuminance_raw"
event_device_mask = "/dev/input/event*"
event_device_name = "Asus WMI hotkeys"
enable_max_brightness_mode = false
filename_for_sensor_activation = ""

[kalman]
q = 1
r = 20
covariance = 10

[light]
points_count = 13

illuminance_0 = 0
light_0 = 0

illuminance_1 = 20
light_1 = 1

illuminance_2 = 300
light_2 = 3

illuminance_3 = 700
light_3 = 4

illuminance_4 = 1100
light_4 = 5

illuminance_5 = 7100
light_5 = 10

illuminance_6 = 20000
light_6 = 20

illuminance_7 = 30000
light_7 = 25

illuminance_8 = 60000
light_8 = 35

illuminance_9 = 70000
light_9 = 45

illuminance_10 = 100000
light_10 = 70

illuminance_11 = 300000
light_11 = 85

illuminance_12 = 400000
light_12 = 95
